All:
	cat ./templates/header.html > new.html
	cat ./posts/newpost.html >> new.html
	cat ./templates/footer.html >> new.html

production:
	cp index.html index.html.bak
	cat ./templates/header.html > index.html
	cat ./posts/post12.html >> index.html
	cat ./posts/post11.html >> index.html
	cat ./posts/post10.html >> index.html
	cat ./posts/post9.html >> index.html
	cat ./posts/post8.html >> index.html
	cat ./posts/post7.html >> index.html
	cat ./posts/post6.html >> index.html
	cat ./posts/post5.html >> index.html
	cat ./posts/post4.html >> index.html
	cat ./posts/post3.html >> index.html
	cat ./posts/post2.html >> index.html
	cat ./posts/post1.html >> index.html
	cat ./templates/footer.html >> index.html

productionscrap:
	cat ./templates/header.html > index.html
	cat ./posts/post12.html >> index.html
	cat ./posts/post11.html >> index.html
	cat ./posts/post10.html >> index.html
	cat ./posts/post9.html >> index.html
	cat ./posts/post8.html >> index.html
	cat ./posts/post7.html >> index.html
	cat ./posts/post6.html >> index.html
	cat ./posts/post5.html >> index.html
	cat ./posts/post4.html >> index.html
	cat ./posts/post3.html >> index.html
	cat ./posts/post2.html >> index.html
	cat ./posts/post1.html >> index.html
	cat ./templates/footer.html >> index.html

